// The committed validation results (generated by `cd demo && npm run validate`). The dashboard never re-types
// these numbers: it reads the same JSON files the report is generated from.
import baselineMain from '../../../validation/baseline/main.json'
import baselineHoldout from '../../../validation/baseline/holdout.json'
import candidateMain from '../../../validation/candidate-graded/main.json'
import candidateHoldout from '../../../validation/candidate-graded/holdout.json'
import finalMain from '../../../validation/final/main.json'
import finalHoldout from '../../../validation/final/holdout.json'
import type { CaseResult, Summary } from '../../../shared/validation.mjs'

export interface SensPoint { depth: number; headroom: number; deviationBps: number; capitalUsd: number; costUsd: number; extractableUsd: number; ratio: number | null }
export interface ValidationFile {
  meta: { rules: 'baseline' | 'candidate-graded' | 'final'; ruleDescription: string; suite: 'main' | 'holdout'; generatedAt: string; durationSeconds: number; gitCommit: string | null; workingTreeClean: boolean; forge: string | null; network: string; command: string }
  config: Record<string, number | string>
  summary: Summary
  cases: CaseResult[]
  sensitivity?: { depths: number[]; deviationsBps: number[]; headrooms: number[]; points: SensPoint[]; verdicts: { depth: number; headroom: number; verdict: string; bestDeviationBps: number; bestRatio: number | null }[] }
}

const cast = (x: unknown) => x as ValidationFile
export const RESULTS = {
  baseline: { main: cast(baselineMain), holdout: cast(baselineHoldout) },
  candidate: { main: cast(candidateMain), holdout: cast(candidateHoldout) },
  final: { main: cast(finalMain), holdout: cast(finalHoldout) },
}
/** The headline result set: final rules, main suite. */
export const VALIDATION = RESULTS.final.main
export const caseById = (id: string, set: ValidationFile = VALIDATION) => set.cases.find((c) => c.id === id)

export const OUTCOME_TONE = { TP: 'ok', TN: 'ok', MATCH: 'ok', FP: 'watch', FN: 'danger', MISMATCH: 'danger' } as const
export const OUTCOME_TEXT = {
  TP: 'True positive', TN: 'True negative', FP: 'False positive', FN: 'False negative', MATCH: 'Policy match', MISMATCH: 'Policy mismatch',
} as const

export const pct = (x: number | null) => (x == null ? 'n/a' : `${(x * 100).toFixed(1)}%`)
export const secs = (s: number | null) => (s == null ? '—' : s < 120 ? `${s} s` : s < 7200 ? `${Math.round(s / 60)} min` : `${(s / 3600).toFixed(1)} h`)
