// Sepolia Testnet Runner: Multipli baseline vs ASO-protected lending on Ethereum Sepolia.
//
// Usage:
//   cd demo && npm run demo:sepolia
//   cd demo && npm run demo:sepolia -- --with-waits
//
// Requires:
//   - deployments/11155111.json (generated by script/DeploySepolia.s.sol)
//   - .env.sepolia with SEPOLIA_RPC_URL, SEPOLIA_RELAYER_KEY, and SOURCE_KEY_1..5

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  createPublicClient,
  createWalletClient,
  http,
  ContractFunctionRevertedError,
  BaseError,
  formatUnits,
} from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { sepolia } from "viem/chains";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SEPOLIA_CHAIN_ID = 11155111;
const WITH_WAITS = process.argv.includes("--with-waits");

// ------------------------------------------------------------------ env loader
function loadEnv(filePath) {
  if (!existsSync(filePath)) return;
  const lines = readFileSync(filePath, "utf8").split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq > 0) {
      const key = trimmed.slice(0, eq).trim();
      const val = trimmed.slice(eq + 1).trim();
      if (!process.env[key]) process.env[key] = val;
    }
  }
}
loadEnv(join(ROOT, ".env.sepolia"));

const RPC = process.env.SEPOLIA_RPC_URL || "https://ethereum-sepolia-rpc.publicnode.com";
const RELAYER_KEY = process.env.SEPOLIA_RELAYER_KEY;
const SOURCE_KEYS = [
  process.env.SOURCE_KEY_1,
  process.env.SOURCE_KEY_2,
  process.env.SOURCE_KEY_3,
  process.env.SOURCE_KEY_4,
  process.env.SOURCE_KEY_5,
].filter(Boolean);

const C = {
  g: "\x1b[32m",
  r: "\x1b[31m",
  y: "\x1b[33m",
  c: "\x1b[36m",
  b: "\x1b[1m",
  d: "\x1b[2m",
  x: "\x1b[0m",
};
const log = (...a) => console.log(...a);
const title = (t) => log(`\n${C.b}${C.c}━━ ${t} ${"━".repeat(Math.max(0, 72 - t.length))}${C.x}`);
const note = (t) => log(`   ${C.d}${t}${C.x}`);
const etherscan = (hash) => `https://sepolia.etherscan.io/tx/${hash}`;

const abi = (file, name) => JSON.parse(readFileSync(join(ROOT, "out", file, `${name}.json`))).abi;

const scenariosResults = [];

async function main() {
  title("ASO Sentinel — Sepolia Testnet Runner");

  // Validate environment credentials
  if (!RELAYER_KEY) {
    throw new Error("Missing SEPOLIA_RELAYER_KEY in .env.sepolia. Please see .env.sepolia.example.");
  }
  if (SOURCE_KEYS.length !== 5) {
    throw new Error("Missing SOURCE_KEY_1..5 in .env.sepolia. Exactly 5 source keys are required.");
  }

  // Load deployment manifest
  const manifestPath = join(ROOT, "deployments", "11155111.json");
  if (!existsSync(manifestPath)) {
    throw new Error(
      "Missing deployments/11155111.json. Run forge script script/DeploySepolia.s.sol --broadcast first."
    );
  }
  const D = JSON.parse(readFileSync(manifestPath, "utf8"));

  // ------------------------------------------------------------------ client setup
  const pc = createPublicClient({ chain: sepolia, transport: http(RPC), pollingInterval: 2000 });
  const chainId = await pc.getChainId();
  if (chainId !== SEPOLIA_CHAIN_ID) {
    throw new Error(`CRITICAL SAFETY CHECK: Expected Sepolia (${SEPOLIA_CHAIN_ID}), got ${chainId}`);
  }

  const relayerAccount = privateKeyToAccount(RELAYER_KEY);
  const wallet = createWalletClient({ account: relayerAccount, chain: sepolia, transport: http(RPC) });

  // Sources (strictly ascending by address)
  const sources = SOURCE_KEYS.map((k) => privateKeyToAccount(k)).sort((a, b) =>
    BigInt(a.address) < BigInt(b.address) ? -1 : 1
  );

  const balance = await pc.getBalance({ address: relayerAccount.address });
  note(`Relayer:  ${relayerAccount.address} (${formatUnits(balance, 18)} Sepolia ETH)`);
  note(`Target:   Chain ID ${chainId} (Sepolia) via ${RPC}`);
  note(`Vat:      Baseline ${D.baselineVat} | Protected ${D.protectedVat}`);
  note(`Sentinel: ${D.sentinel} | Verifier: ${D.verifier}`);

  if (balance === 0n) {
    throw new Error(`Relayer account ${relayerAccount.address} has 0 Sepolia ETH. Please fund it from a faucet.`);
  }

  const A = {
    vat: abi("vat.sol", "Vat"),
    spot: abi("spot.sol", "Spotter"),
    osm: abi("osm.sol", "OSM"),
    adapter: abi("adapter.sol", "PriceFeedAdapter"),
    join: abi("join.sol", "GemJoin5"),
    verifier: abi("ASOVerifier.sol", "ASOVerifier"),
    sentinel: abi("ASOSentinel.sol", "ASOSentinel"),
    feed: abi("MockAggregator.sol", "MockAggregator"),
    gem: abi("MockRWA.sol", "MockRWA"),
  };

  const ILK = D.ilk;
  const WAD = 10n ** 18n;
  const RAD = 10n ** 45n;
  const HOUR = 3600n;

  const read = (address, a, functionName, args = []) =>
    pc.readContract({ address, abi: a, functionName, args, account: relayerAccount.address });

  // ------------------------------------------------------------------ transaction sender
  async function tx(label, address, a, functionName, args, expect = "success", scenario = null) {
    let reason = null;
    try {
      await pc.simulateContract({ account: relayerAccount, address, abi: a, functionName, args });
    } catch (e) {
      const rev = e instanceof BaseError ? e.walk((x) => x instanceof ContractFunctionRevertedError) : null;
      if (rev?.data?.errorName) reason = `${rev.data.errorName}(${(rev.data.args ?? []).join(", ")})`;
      else reason = rev?.reason ?? e.shortMessage ?? "Contract reverted";
    }

    // For expected reverts, use fixed gas limit so tx is mined as reverted
    const gas = expect === "revert" ? 350_000n : undefined;
    let hash;
    try {
      hash = await wallet.writeContract({ address, abi: a, functionName, args, gas });
    } catch (e) {
      // If node rejected sendTransaction outright, record and return
      const pass = expect === "revert";
      log(`   ${pass ? C.g + "✔" : C.r + "✖"} ${label} (rejected before mempool: ${reason || e.shortMessage})`);
      if (scenario) {
        scenariosResults.push({ scenario, label, expect, actual: `rejected: ${reason || e.shortMessage}`, pass });
      }
      return { ok: false, reason, rc: null };
    }

    const rc = await pc.waitForTransactionReceipt({ hash });
    const ok = rc.status === "success";
    const pass = (expect === "success") === ok;
    const mark = ok ? `${C.g}✔ SUCCESS${C.x}` : `${C.r}✖ REVERTED${C.x}`;

    log(`   ${mark} ${label}`);
    log(`     ${C.d}tx: ${etherscan(hash)}${reason ? ` | reason: ${C.y}${reason}${C.d}` : ""}${C.x}`);

    if (scenario) {
      scenariosResults.push({
        scenario,
        label,
        expect,
        actual: ok ? "success" : `reverted: ${reason}`,
        txHash: hash,
        etherscanUrl: etherscan(hash),
        pass,
      });
    }
    return { ok, reason, rc, hash };
  }

  // ------------------------------------------------------------------ block time & EIP-712 attestations
  const getBlockTime = async () => (await pc.getBlock()).timestamp;

  const domain = { name: "ASO Verifier", version: "1", chainId: SEPOLIA_CHAIN_ID, verifyingContract: D.verifier };
  const types = {
    PriceAttestation: [
      { name: "profileId", type: "bytes32" },
      { name: "price", type: "uint256" },
      { name: "validAfter", type: "uint64" },
      { name: "validUntil", type: "uint64" },
      { name: "nonce", type: "uint64" },
      { name: "source", type: "address" },
    ],
  };

  let nonce = 0n;
  async function signRound(usdPrices, n = ++nonce, signersList = sources) {
    const t = await getBlockTime(); // Strictly uses block timestamp
    const atts = [],
      sigs = [];
    for (let i = 0; i < usdPrices.length; i++) {
      const a = {
        profileId: D.profileId,
        price: BigInt(usdPrices[i]) * WAD,
        validAfter: t,
        validUntil: t + HOUR,
        nonce: n,
        source: signersList[i].address,
      };
      atts.push(a);
      sigs.push(
        await signersList[i].signTypedData({ domain, types, primaryType: "PriceAttestation", message: a })
      );
    }
    return { atts, sigs };
  }

  // ------------------------------------------------------------------ setup: prime OSM
  title("Step 0: Priming Multipli OSM on Sepolia");
  const [, osmHas] = await read(D.osm, A.osm, "peek");
  if (!osmHas) {
    log("   Multipli OSM is uninitialized (cur.has == false). Performing initial poke...");
    await tx("OSM.poke() (first step)", D.osm, A.osm, "poke", []);

    log("   Waiting 65s for OSM hop interval (osmHop = 60s) by Sepolia block time...");
    const startT = await getBlockTime();
    while (true) {
      await new Promise((r) => setTimeout(r, 12000));
      const currentT = await getBlockTime();
      const elapsed = Number(currentT - startT);
      process.stdout.write(`\r   Elapsed block time: ${elapsed}s / 65s...`);
      if (elapsed >= 65) {
        log("\n   OSM hop interval satisfied. Performing second poke...");
        break;
      }
    }

    await tx("OSM.poke() (second step, activates price)", D.osm, A.osm, "poke", []);
    await tx("Baseline Spotter.poke()", D.baselineSpotter, A.spot, "poke", [ILK]);
    await tx("Protected Spotter.poke()", D.protectedSpotter, A.spot, "poke", [ILK]);
  } else {
    note("OSM is already primed and serving active price.");
  }

  // ------------------------------------------------------------------ collateral deposit
  title("Step 1: Deposit Collateral (100 mPAXG)");
  const depositWad = 100n * WAD;
  await tx("Approve mPAXG (Baseline Join)", D.gem, A.gem, "approve", [D.baselineJoin, depositWad]);
  await tx("GemJoin5.join (Baseline)", D.baselineJoin, A.join, "join", [relayerAccount.address, depositWad]);
  await tx("Vat.frob collateral (Baseline)", D.baselineVat, A.vat, "frob", [
    ILK,
    relayerAccount.address,
    relayerAccount.address,
    relayerAccount.address,
    depositWad,
    0n,
  ]);

  await tx("Approve mPAXG (Protected Join)", D.gem, A.gem, "approve", [D.protectedJoin, depositWad]);
  await tx("GemJoin5.join (Protected)", D.protectedJoin, A.join, "join", [relayerAccount.address, depositWad]);
  await tx("Vat.frob collateral (Protected)", D.protectedVat, A.vat, "frob", [
    ILK,
    relayerAccount.address,
    relayerAccount.address,
    relayerAccount.address,
    depositWad,
    0n,
  ]);

  // ------------------------------------------------------------------ scenario S1
  title("Scenario S1: Valid Round + Sentinel Headroom + Borrow");
  const r1 = await signRound([2500, 2500, 2500]);
  await tx("ASOVerifier.submitRound (3-of-5 quorum, $2,500)", D.verifier, A.verifier, "submitRound", [
    r1.atts,
    r1.sigs,
  ], "success", "S1");

  await tx("ASOSentinel.poke() (opens bounded headroom)", D.sentinel, A.sentinel, "poke", [], "success", "S1");

  const borrowWad = 10_000n * WAD;
  await tx("Borrow 10,000 rwaUSD on BASELINE Vat", D.baselineVat, A.vat, "frob", [
    ILK,
    relayerAccount.address,
    relayerAccount.address,
    relayerAccount.address,
    0n,
    borrowWad,
  ], "success", "S1");

  await tx("Borrow 10,000 rwaUSD on PROTECTED Vat", D.protectedVat, A.vat, "frob", [
    ILK,
    relayerAccount.address,
    relayerAccount.address,
    relayerAccount.address,
    0n,
    borrowWad,
  ], "success", "S1");

  // ------------------------------------------------------------------ scenario S4
  title("Scenario S4: Tampered / Forged Signature Reverts");
  const r4 = await signRound([2500, 2500, 2500]);
  // Tamper signature 0
  const tamperedSig = "0x" + "00".repeat(65);
  await tx("Submit tampered signature -> must revert", D.verifier, A.verifier, "submitRound", [
    r4.atts,
    [tamperedSig, r4.sigs[1], r4.sigs[2]],
  ], "revert", "S4");

  // ------------------------------------------------------------------ scenario S5
  title("Scenario S5: Replayed Nonce Reverts");
  await tx("Submit replayed nonce round -> must revert", D.verifier, A.verifier, "submitRound", [
    r1.atts,
    r1.sigs,
  ], "revert", "S5");

  // ------------------------------------------------------------------ scenario S3 & S8
  title("Scenario S3: Divergent Sources (Disputed) + Repayment (S8)");
  const r3 = await signRound([2400, 2500, 2600]); // > 1% spread
  await tx("ASOVerifier.submitRound (>1% spread -> DISPUTED)", D.verifier, A.verifier, "submitRound", [
    r3.atts,
    r3.sigs,
  ], "success", "S3");

  await tx("ASOSentinel.poke() (throttles line to 0)", D.sentinel, A.sentinel, "poke", [], "success", "S3");

  await tx("Borrow while restricted -> must revert", D.protectedVat, A.vat, "frob", [
    ILK,
    relayerAccount.address,
    relayerAccount.address,
    relayerAccount.address,
    0n,
    borrowWad,
  ], "revert", "S3");

  // S8: Repayments must remain unblocked while restricted
  await tx("Repay 5,000 rwaUSD while restricted (S8)", D.protectedVat, A.vat, "frob", [
    ILK,
    relayerAccount.address,
    relayerAccount.address,
    relayerAccount.address,
    0n,
    -5_000n * WAD,
  ], "success", "S8");

  // ------------------------------------------------------------------ scenario S7
  title("Scenario S7: Recovery Round Restores Borrowing");
  const r7 = await signRound([2500, 2500, 2500]);
  await tx("ASOVerifier.submitRound (agreeing data restores OK)", D.verifier, A.verifier, "submitRound", [
    r7.atts,
    r7.sigs,
  ], "success", "S7");

  await tx("ASOSentinel.poke() (restores headroom)", D.sentinel, A.sentinel, "poke", [], "success", "S7");

  await tx("Borrow on PROTECTED Vat after recovery -> succeeds", D.protectedVat, A.vat, "frob", [
    ILK,
    relayerAccount.address,
    relayerAccount.address,
    relayerAccount.address,
    0n,
    borrowWad,
  ], "success", "S7");

  // ------------------------------------------------------------------ scenario S6 (instant variant)
  title("Scenario S6: Instant Market Drop (Feeder frozen at $2,500, real price $1,500)");
  // Feeder remains $2,500, OSM serves $2,500. Sources attest real crash to $1,500.
  const r6 = await signRound([1500, 1500, 1500]);
  await tx("ASOVerifier.submitRound (attests real price dropped to $1,500)", D.verifier, A.verifier, "submitRound", [
    r6.atts,
    r6.sigs,
  ], "success", "S6");

  await tx("ASOSentinel.poke() (detects Vat price above attested -> RESTRICTS)", D.sentinel, A.sentinel, "poke", [], "success", "S6");

  // Baseline has no sentinel: still lends against stale $2,500 price
  await tx("Baseline Vat still allows borrow at stale price (Bad Debt)", D.baselineVat, A.vat, "frob", [
    ILK,
    relayerAccount.address,
    relayerAccount.address,
    relayerAccount.address,
    0n,
    borrowWad,
  ], "success", "S6");

  // Protected Vat is restricted: blocks borrow
  await tx("Protected Vat frob -> reverts with Vat/ceiling-exceeded", D.protectedVat, A.vat, "frob", [
    ILK,
    relayerAccount.address,
    relayerAccount.address,
    relayerAccount.address,
    0n,
    borrowWad,
  ], "revert", "S6");

  // ------------------------------------------------------------------ optional S2
  if (WITH_WAITS) {
    title("Scenario S2: Attestation Expiry (Waiting 310s for maxAge = 300s)");
    log("   Waiting 310s by block time for attested round to become STALE...");
    const s2Start = await getBlockTime();
    while (true) {
      await new Promise((r) => setTimeout(r, 15000));
      const el = Number((await getBlockTime()) - s2Start);
      process.stdout.write(`\r   Elapsed: ${el}s / 310s...`);
      if (el >= 310) {
        log("\n   Staleness elapsed.");
        break;
      }
    }
    await tx("ASOSentinel.poke() -> restricts on STALE ASO data", D.sentinel, A.sentinel, "poke", [], "success", "S2");
    await tx("Borrow on protected Vat -> reverts", D.protectedVat, A.vat, "frob", [
      ILK,
      relayerAccount.address,
      relayerAccount.address,
      relayerAccount.address,
      0n,
      borrowWad,
    ], "revert", "S2");
  }

  // ------------------------------------------------------------------ save report
  const reportPath = join(ROOT, "deployments", "11155111-scenarios.json");
  writeFileSync(reportPath, JSON.stringify(scenariosResults, null, 2), "utf8");
  log(`\n${C.b}${C.g}All testnet scenarios completed!${C.x}`);
  log(`Saved scenario report to ${reportPath}`);
}

main().catch((e) => {
  console.error("\nRunner error:", e.message || e);
  process.exit(1);
});
